version: "3.9"

services:
    web:
        build:
            context: ./
            dockerfile: Dockerfile
            target: prod
        command: ["./auth"]
    kafka:
        environment:
            - ALLOW_PLAINTEXT_LISTENER=no