# for development environment
version: "3.9"

services:
    web:
        build:
            context: ./
            dockerfile: Dockerfile
            target: dev
        volumes:
          - .:/usr/src/app
        command: ["cargo", "watch", "-x", "run", "-p", "auth"]
