version: "3.9"
services:
    zookeeper:
        image: "bitnami/zookeeper:3.5"
        ports:
            - "2181:2181"
        restart: unless-stopped
        environment:
            - ALLOW_ANONYMOUS_LOGIN=yes
    kafka:
        image: "bitnami/kafka:3.2"
        hostname: kafka
        depends_on: zookeeper
        ports:
            - "9092:9092"
        environment:
            - KAFKA_BROKER_ID=1
            - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
            - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:127.0.0.1:9092
            - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
            - ALLOW_PLAINTEXT_LISTENER=yes
        volumes:
            - .local_kafka_persist:/bitnami/kafka
    redis:
        image: redis
        environment:
            redis_uri: ${REDIS_URI}
    postgres:
        hostname: db
        image: postgres:14.2
        volumes:
            - ./data:/docker-entrypoint-initdb.d
            - pgdata:/var/lib/postgresql/data
        restart: on-failure:2
        environment:
            POSTGRES_USERNAME: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_PORT: ${DB_PORT}
            POSTGRES_HOST: ${DB_HOST}
            POSTGRES_NAME: ${DB_NAME}
        ports:
          - ${DB_PORT}:5432
    web:
        depends_on:
            - postgres
            - redis
        ports:
          - ${APP_PORT}:8000
        links:
          - postgres
        environment:
            app__db__username: ${DB_USERNAME:-postgres}
            app__db__password: ${DB_PASSWORD:?database password not set}
            app__db__port: ${DB_PORT:-5432}
            app__db__host: db
            app__db__name: ${DB_NAME:-play_auth}
            app__db__require_ssl: ${DB_SSL:-false}
            app__email__smtp_server: ${SMTP_SERVER}
            app__email__smtp_user: ${SMTP_USER}
            app__email__smtp_pass: ${SMTP_PASS}
            app__app_env: ${APP_ENV:-test}
            app__app__m_cost: ${M_COST}
            app__app__t_cost: ${T_COST}
            app__app__p_cost: ${P_COST}
            app__app__port: ${APP_PORT}
            app__app_name: ${APP_NAME}
            app__redis_uri: ${REDIS_URI}
            app__app__frontend_url: ${FRONTEND_URL}
            app__app__jwt_secret: ${JWT_SECRET}
networks:
    webnet:
        driver: bridge
    app-tier:
        driver: bridge
volumes:
    pgdata:
    static_volume:
