# for development environment
version: "3.9"

services:
    web:
        build:
            context: ./
            dockerfile: Dockerfile
            target: dev
        volumes:
          - ".:/usr/src/app"
        command: ["/bin/bash", "./scripts/init_db.sh"]
    db:
        volumes:
          - "target-cache:/usr/src/app/target"
        
volumes:
    target-cache: