version: "3.9"

services:
    web:
        build:
            context: ./
            dockerfile: Dockerfile
            target: dev
        volumes:
          - ".:/usr/src/app"
          - "target-cache:/usr/src/app/target"
        command: ["cargo", "watch", "-x", "run", "-p", "auth"]
volumes:
    target-cache: