db:
  host: localhost
  port: 5432
  username: tolumideshopein
  password: password
  database_name: play_auth
  require_ssl: false
app:
  port: 8000
  env: local
  m_cost: 17000
  p_cost: 3
  t_cost: 2
  jwt_secret: aSampleYUIJWTYIOLSNDKLSECZZRETdsjk9210921secret
  frontend_url: "https://samplefrontendurl.com"
# redis_uri: "redis://127.0.0.1:6379"
redis_uri: "redis://127.0.0.1/"
# email:
