db:
  host: ${DB_LOCAL_HOST}
  port: ${DB_LOCAL_PORT}
  # port: 5432
  username: ${DB_LOCAL_USERNAME}
  password: ${DB_LOCAL_PASSWORD}
  database_name: ${DB_LOCAL_NAME}
  # db_url: ${DB_URL}
  require_ssl: false
# db:
#   host: ${DB_LOCAL_HOST}
#   port: 5432
#   username: tolumideshopein
#   password: password
#   database_name: play_auth
#   require_ssl: false
