name: Play_auth CI

on:
  pull_request:

env:
  CARGO_TERM_COLOR: always
  DB_USERNAME: "postgres"
  DB_PASSWORD: "postgres"
  DB_PORT: "5432"
  DB_HOST: "postgres"
  DB_NAME: "authey_test"
  M_COST: 1250
  T_COST: 2
  P_COST: 2
  APP_PORT: 6005
  APP_NAME: "eleniyan"
  REDIS_URI: "redis://redis:6379"
  FRONTEND_URL: "https://sample.example.com"
  JWT_SECRET: "AProbablylONGJWT923PU32NMSNDKLTOKEN20//12=2394309ORSECRET"

concurrency:
  group: ${{ github.head_ref || github.run_id }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_test:
    name: Runner
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchains:
          - stable
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Start containers
        run: make play_test
      - name: Stop containers
        if: always()
        run: make play_all_down
